
name: Continuous Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/hands-on-notes-api-django
            git checkout main               # pastikan berada di branch yang benar
            git pull origin main
            source .venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate        # jalankan migrasi
            sudo systemctl restart gunicorn # reload aplikasi