name: Continuous Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DJANGO_SETTINGS_MODULE,APP_PORT,DATABASE_URL,JWT_SECRET,CORS_ORIGIN,DOMAIN
          script: |
            cd ~/hands-on-notes-api-django
            git checkout main
            git pull origin main
            cat > .env << EOF
            DEBUG=False
            SECRET_KEY=$JWT_SECRET
            DATABASE_URL=$DATABASE_URL
            ALLOWED_HOSTS=localhost,127.0.0.1,$DOMAIN
            CORS_ALLOWED_ORIGINS=$CORS_ORIGIN
            EOF
            source .venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart gunicorn
        env:
          DJANGO_SETTINGS_MODULE: project.settings.prod
          APP_PORT: ${{ secrets.APP_PORT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
          DOMAIN: ${{ secrets.DOMAIN }}